#!/bin/bash                                                                                                                                                                                                                                                 
#SBATCH --job-name=linc_cal                                                                                                                                                                                                                           
#SBATCH -p lofar                                                                                                                                                                                                                                            
#SBATCH --time=96:00:00                                                                                                                                                                                                                                     
#SBATCH -N 1                                                                                                                                                                                                                                                
#SBATCH --ntasks-per-node=32                                                                                                                                                                                                                                
#SBATCH --nodelist=you can specify here a particular node                                                                                                                                                                                                                           
#SBATCH --exclusive                                                                                                                                                                                                                                         
#SBATCH --output=/path/to/subtraction.log                                                                                                                                                                                                          
#SBATCH --error=/path/to/subtraction.err                                                                                                                                                                                                           
#SBATCH --mail-type=ALL                                                                                                                                                                                                                                     
#SBATCH --mail-user=youremail@email.com                                                                                                                                                                                                             
#SBATCH --chdir=/local/work/directory/                                                                                                                                                                                                                     

echo "Hostname is" $(hostname)
singularity exec -B /folders/to/bind/,/even/more/then/one /path/to/singularity.sif sh linc_calibrator_singlenode.sh